name: PE SpringBoot Application
'on':
- push
env:
  name: Sample springboot application
  namespace: statestreet_mortgage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: adopt
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: 'Hello World'
      description: 'Greet someone and record the time'
      inputs:
        who-to-greet:  # id of input
          description: 'Who to greet'
          required: true
          default: 'World'
      outputs:
        time: # id of output
          description: 'The time we greeted you'
      runs:
        using: 'docker'
        image: 'Dockerfile'
        args:
          - ${{ inputs.who-to-greet }}


