name: PE SpringBoot Application
'on':
  push:
  workflow_dispatch:
    inputs: 
        value:
          required: true
          type: string
env:
  name: Sample springboot application
  GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GKE_SHARED_SECRET }}'
  PROJECT_ID: "shared-svc1-project"
  CLUSTER_NAME: "pde-gke"
  ZONE: "europe-west1"
  NAMESPACE: "sts-investment"
  CLUSTER_IP: 35.189.222.183
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: set_var
      run: |
        content="${{ github.event.inputs.value }}"
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "::set-output name=packageJson::$content"
        
    - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).Name}}"
