name: Platform-Workspace
on:
   push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      run: echo "hello"
    - id: 'auth2'
      name: 'Authenticate to Google Cloud'
      run:  echo "hello"
    - id: 'auth3'
      name: 'Authenticate to Google Cloud'
      run:  echo "hello"
    - id: 'auth4'
      name: 'Authenticate to Google Cloud'
      run:  echo "hello"
    - id: 'auth5'
      name: 'Authenticate to Google Cloud'
      run:  echo "hello"
      
    
