name: PE SpringBoot Application
'on':
- push
env:
  name: Sample springboot application
  namespace: statestreet_mortgage
  GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GKE_SHARED_SECRET }}'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SHARED_SECRET }}'
    - name: Activate Service Account
      run: |
        gcloud config set account shared-k8s@shared-svc1-project.iam.gserviceaccount.com
        gcloud auth activate-service-account shared-k8s@shared-svc1-project.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS --project=shared-svc1-project

    - name: Create Namespace
      run: |
        curl -X POST \
        -H "Authorization: Bearer $(gcloud auth print-access-token)" \
        -H "Content-Type: application/json" \
        -d '{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"mortgage-shared"}}' \
        --insecure \
        "https://35.189.222.183/api/v1/namespaces"
 
    - name: Create KSA
      run: |
        gcloud container clusters get-credentials pde-gke --zone=europe-west1
        kubectl create serviceaccount ksa-mortgage-shared-04 --namespace mortgage-shared --insecure-skip-tls-verify
        gcloud projects add-iam-policy-binding shared-svc1-project --member "serviceAccount:shared-test-sa@shared-svc1-project.iam.gserviceaccount.com" --role "roles/spanner.viewer"
        kubectl annotate serviceaccount ksa-mortgage-shared --namespace mortgage-shared iam.gke.io/gcp-service-account=shared-test-sa@shared-svc1-project.iam.gserviceaccount.com --insecure-skip-tls-verify

