name: PE SpringBoot Application
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: 
      Name: 
        required: true
        type: string
      CostCentre: 
        required: true
        type: string
      CloudPlatform: 
        required: true
        type: string
      AADGroupId: 
        required: true
        type: string
env:
  name: Sample springboot application
  GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GKE_SHARED_SECRET }}'
  PROJECT_ID: "shared-svc1-project"
  CLUSTER_NAME: "pde-gke"
  ZONE: "europe-west1"
  CLUSTER_IP: 35.189.222.183
  USER_GKE_GSA: shared-test-sa@shared-svc1-project.iam.gserviceaccount.com
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SHARED_SECRET }}'
    - name: Activate Service Account
      run: |
        gcloud config set account shared-k8s@shared-svc1-project.iam.gserviceaccount.com
        gcloud auth activate-service-account shared-k8s@shared-svc1-project.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS --project=$PROJECT_ID

    - name: Create Namespace
      id: create_ns
      run: |
        echo "${{ github.event.inputs.Name }}"
        curl -X POST \
        -H "Authorization: Bearer $(gcloud auth print-access-token)" \
        -H "Content-Type: application/json" \
        -d '{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"${{ github.event.inputs.Name }}"}}' --insecure "https://$CLUSTER_IP/api/v1/namespaces"
      # continue-on-error: false
    - name: Create KSA
      id: create_ksa
      run: |
        gcloud container clusters get-credentials pde-gke --zone=$ZONE
        kubectl create serviceaccount ksa-${{ github.event.inputs.Name }} --namespace ${{ github.event.inputs.Name }} --insecure-skip-tls-verify
        gcloud projects add-iam-policy-binding $PROJECT_ID --member "serviceAccount:$USER_GKE_GSA" --role "roles/spanner.viewer"
        kubectl annotate serviceaccount ksa-${{ github.event.inputs.Name }} --namespace ${{ github.event.inputs.Name }}  iam.gke.io/gcp-service-account=$USER_GKE_GSA --insecure-skip-tls-verify
      # continue-on-error: false
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Check on success
      if: steps.create_ns.outputs.status != 'failure' || steps.world.create_ksa.status != 'failure'
      run: |
        output=echo $(python 3 handle-response.py "$CLUSTER_NAME" "${{ github.event.inputs.Name }}" "$ZONE" "$USER_GKE_GSA")
        echo '::set-output name=output'
