name: PE SpringBoot Application
'on':
- push
env:
  name: Sample springboot application
  namespace: statestreet_mortgage
  GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GCP_SECRET }}'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: adopt
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SECRET }}'
        
    - name: Upload to Artifact Registry
      run: |
        gcloud config set artifacts/repository europe-docker.pkg.dev/playpen-yggfkz/eu.gcr.io
        gcloud config set artifacts/location eu-central1
        gcloud config set account github-gcr-service-account@norrin-radd.iam.gserviceaccount.com
      
        gcloud auth activate-service-account playpen-yggfkz-sa@playpen-yggfkz.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS --project=norrin-radd'
    
    



