name: PE SpringBoot Application
'on':
- push
env:
  name: Sample springboot application
  namespace: statestreet_mortgage
  GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GCP_SECRET }}'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SECRET }}'
    
    - name: GKE Job
      run: |
        gcloud auth print-access-token
