name: PE SpringBoot Application
'on':
- push
env:
  name: Sample springboot application
  namespace: statestreet_mortgage
  GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GCP_SECRET }}'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: adopt
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: |
        ./gradlew build
        ls
        cd build/
        ls
        pwd
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SECRET }}'
    - name: Connect to Artifact Registry
      run: |
        gcloud config set artifacts/repository europe-docker.pkg.dev/playpen-yggfkz/eu.gcr.io
        gcloud config set artifacts/location eu-central1
        gcloud config set account playpen-yggfkz-sa@playpen-yggfkz.iam.gserviceaccount.com
        gcloud auth activate-service-account playpen-yggfkz-sa@playpen-yggfkz.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS --project=playpen-yggfkz
    
    - name: Build image and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: eu.gcr.io/playpen-yggfkz/java-hello-app:latest 



